# This tells Stylua to treat this as the root config
project_root = true

# Global options
indent_type = "Tabs"
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 120

# Override for files inside Libs directory (if you want to skip formatting them)
[override]
"Libs/**.lua" = { format = false }
