local function read(path)
    local file = assert(io.open(path, "r"))
    local text = file:read("*a")
    file:close()
    return text
end

local logger = read("!KRT/Controllers/Logger.lua")
local loggerXml = read("!KRT/UI/Logger.xml")
local visuals = read("!KRT/Modules/UI/Visuals.lua")
local listController = read("!KRT/Modules/UI/ListController.lua")

assert(logger:find("calculateLoggerColumnWidths", 1, true), "Logger column widths must be calculated dynamically")
assert(logger:find("getLoggerListContentWidth", 1, true), "Logger list widths must come from visible frame geometry")
assert(logger:find("getLoggerListColumnBudget", 1, true), "Logger column budgets must account for row offsets and gaps")
assert(logger:find("LOGGER_HEADER_COLUMN_GAP", 1, true), "Logger headers must account for visual row gaps")
assert(logger:find("setHeaderWidth", 1, true), "Logger header width application must be centralized")
assert(logger:find("positionLoggerHeaderColumns", 1, true), "Logger header columns must be positioned from row geometry")
assert(logger:find("LOGGER_HEADER_TOP_OFFSET", 1, true), "Logger header positioning must keep a centralized top offset")
assert(logger:find("ensureLoggerHeaderTab", 1, true), "Logger headers must render visible tab chrome")
assert(logger:find("_krtHeaderTop", 1, true), "Logger header tabs must include a visible top edge")
assert(logger:find("_krtHeaderBottom", 1, true), "Logger header tabs must include a visible bottom edge")
assert(logger:find("LOGGER_LOOT_COLUMN_MIN_WIDTHS", 1, true), "Logger loot column minimums must be centralized")
assert(logger:find("LOGGER_LOOT_COLUMN_RATIOS", 1, true), "Logger loot column ratios must be centralized")
assert(logger:find("LOGGER_ATTENDANCE_COLUMN_MIN_WIDTHS", 1, true), "Logger attendance column minimums must be centralized")
assert(logger:find("LOGGER_ATTENDANCE_TIME_COLUMN_MIN_WIDTH", 1, true), "Logger attendance time columns must have a readable minimum")
assert(logger:find("LOGGER_ATTENDANCE_COLUMN_RATIOS", 1, true), "Logger attendance column ratios must be centralized")
assert(logger:find("LOGGER_BOSS_COLUMN_MIN_WIDTHS", 1, true), "Logger boss column minimums must be centralized")
assert(logger:find("LOGGER_BOSS_COLUMN_RATIOS", 1, true), "Logger boss column ratios must be centralized")
assert(logger:find("LOGGER_RAID_COLUMN_MIN_WIDTHS", 1, true), "Logger raid column minimums must be centralized")
assert(logger:find("LOGGER_RAID_COLUMN_RATIOS", 1, true), "Logger raid column ratios must be centralized")
assert(logger:find("applyLootListColumnWidths", 1, true), "Logger loot header widths must be applied centrally")
assert(logger:find("applyLootRowColumnWidths", 1, true), "Logger loot row widths must be applied centrally")
assert(logger:find("applyAttendanceListColumnWidths", 1, true), "Logger attendance header widths must be applied centrally")
assert(logger:find("applyAttendanceRowColumnWidths", 1, true), "Logger attendance row widths must be applied centrally")
assert(logger:find("applyBossListColumnWidths", 1, true), "Logger boss header widths must be applied centrally")
assert(logger:find("applyBossRowColumnWidths", 1, true), "Logger boss row widths must be applied centrally")
assert(logger:find("LOGGER_LOOT_ROW_HEIGHT", 1, true), "Logger loot row height must be explicit")
assert(logger:find("LOGGER_COMPACT_ROW_HEIGHT", 1, true), "Logger compact row height must be explicit")
assert(logger:find("ToggleLootHistory", 1, true), "Logger must expose a dedicated Loot History opener")
assert(logger:find("ToggleRaidAttendance", 1, true), "Logger must expose a dedicated Raid Attendance opener")
assert(logger:find("KRTRaidAttendanceRaids", 1, true), "Logger must bind a separate Raid Attendance raids panel")
assert(logger:find("KRTRaidAttendanceRaidAttendees", 1, true), "Logger must bind a separate Raid Attendance attendees panel")
assert(logger:find("KRTRaidAttendanceBosses", 1, true), "Logger must bind a separate Raid Attendance boss participation panel")
assert(logger:find("setLoggerRowIndex", 1, true), "Logger row striping must reset on row reuse")
assert(logger:find("setLoggerRowIndex(row, visibleIndex)", 1, true), "Logger row striping must use visible list position")
assert(logger:find("rightInset = 0", 1, true), "Logger lists must keep the existing scrollbar inset policy")
assert(logger:find("setPanelVisible%(refs%.bossAttendees, false%)", 1, false), "Logger refresh must keep the boss attendee panel hidden")

assert(loggerXml:find('Frame name="KRTRaidAttendance"', 1, true), "Logger XML must define a distinct Raid Attendance frame")
assert(loggerXml:find('Frame name="KRTRaidAttendanceRaids"', 1, true), "Raid Attendance XML must define a separate raids list")
assert(loggerXml:find('Frame name="KRTRaidAttendanceRaidAttendees"', 1, true), "Raid Attendance XML must define a separate attendees list")
assert(loggerXml:find('Frame name="KRTRaidAttendanceBosses"', 1, true), "Raid Attendance XML must define a separate boss participation list")

assert(visuals:find("isLoggerRow%(row%)", 1, false), "Logger row visuals must stay scoped to Logger rows")
assert(visuals:find("0%.08, 0%.52, 0%.10", 1, false), "Logger selected rows must remain green")
assert(listController:find("cfg.drawRow(row, it, i)", 1, true), "ListController must pass visible row position to drawers")
assert(listController:find("syncScrollChildWidth", 1, true), "ListController rows must span the current scroll frame width")

print("logger visual refresh source contract passed")
