local function read(path)
    local file = assert(io.open(path, "r"))
    local text = file:read("*a")
    file:close()
    return text
end

local logger = read("!KRT/Controllers/Logger.lua")
local loggerXml = read("!KRT/UI/Logger.xml")
local frames = read("!KRT/Modules/UI/Frames.lua")
local visuals = read("!KRT/Modules/UI/Visuals.lua")
local listController = read("!KRT/Modules/UI/ListController.lua")

assert(logger:find("calculateLoggerColumnWidths", 1, true), "Logger column widths must be calculated dynamically")
assert(logger:find("getLoggerListContentWidth", 1, true), "Logger list widths must come from visible frame geometry")
assert(logger:find("getLoggerListColumnBudget", 1, true), "Logger column budgets must account for row offsets and gaps")
assert(logger:find("LOGGER_HEADER_COLUMN_GAP", 1, true), "Logger headers must account for visual row gaps")
assert(logger:find("setHeaderWidth", 1, true), "Logger header width application must be centralized")
assert(logger:find("positionLoggerHeaderColumns", 1, true), "Logger header columns must be positioned from row geometry")
assert(logger:find("LOGGER_HEADER_TOP_OFFSET", 1, true), "Logger header positioning must keep a centralized top offset")
assert(visuals:find("resolveLoggerHeaderTab", 1, true), "Logger headers must render visible tab chrome through shared visuals")
assert(visuals:find("HeaderIlvl", 1, true), "Logger attendance headers must include ilvl for visual styling")
assert(visuals:find("HeaderSpec", 1, true), "Logger attendance headers must include spec for visual styling")
assert(visuals:find("HeaderInspect", 1, true), "Logger attendance headers must include inspect for visual styling")
assert(visuals:find("_krtHeaderTop", 1, true), "Logger header tabs must include a visible top edge")
assert(visuals:find("_krtHeaderBottom", 1, true), "Logger header tabs must include a visible bottom edge")
assert(logger:find("LOGGER_LOOT_COLUMN_MIN_WIDTHS", 1, true), "Logger loot column minimums must be centralized")
assert(logger:find("LOGGER_LOOT_COLUMN_RATIOS", 1, true), "Logger loot column ratios must be centralized")
assert(logger:find("LOGGER_ATTENDANCE_COLUMN_MIN_WIDTHS", 1, true), "Logger attendance column minimums must be centralized")
assert(logger:find("spec = 37", 1, true), "Logger attendance spec column minimum width must be 37")
assert(logger:find("inspect = 324", 1, true), "Logger attendance inspect column minimum width must be 324")
assert(logger:find("LOGGER_ATTENDANCE_TIME_COLUMN_MIN_WIDTH", 1, true), "Logger attendance time columns must have a readable minimum")
assert(logger:find("LOGGER_ATTENDANCE_COLUMN_RATIOS", 1, true), "Logger attendance column ratios must be centralized")
assert(logger:find("RAID_INSPECT_ICON_SIZE = 18", 1, true), "Logger raid inspect icons must be 18px")
assert(logger:find("RAID_SPEC_ICON_SIZE = 17", 1, true), "Logger raid spec icons must be 17px")
assert(logger:find("RAID_INSPECT_ICON_GAP = 1", 1, true), "Logger raid inspect icon gap must be 1px")
assert(logger:find("RAID_SPEC_ICON_GAP = 1", 1, true), "Logger raid spec icon gap must be 1px")
assert(logger:find("RAID_INSPECT_ICON_LEFT_OFFSET", 1, true), "Logger inspect icons must have a 1px left offset constant")
assert(loggerXml:find("$parentInspectItemIcon1", 1, true), "Logger XML must define inspect item icon 1")
assert(loggerXml:find("$parentInspectItemIcon17", 1, true), "Logger XML must define inspect item icon 17")
assert(not logger:find('CreateFrame("Button", nil, row)', 1, true), "Logger must not create anonymous attendance icons in Lua")
assert(not logger:find('CreateFrame("Button", iconName, row', 1, true), "Logger must not create named attendance icon fallback buttons in Lua")
assert(not logger:find('icon:CreateTexture(nil, "ARTWORK")', 1, true), "Logger must not create icon textures in Lua when XML templates are used")
assert(logger:find("LOGGER_BOSS_COLUMN_MIN_WIDTHS", 1, true), "Logger boss column minimums must be centralized")
assert(logger:find("LOGGER_BOSS_COLUMN_RATIOS", 1, true), "Logger boss column ratios must be centralized")
assert(logger:find("LOGGER_RAID_COLUMN_MIN_WIDTHS", 1, true), "Logger raid column minimums must be centralized")
assert(logger:find("LOGGER_RAID_COLUMN_RATIOS", 1, true), "Logger raid column ratios must be centralized")
assert(logger:find("applyLootListColumnWidths", 1, true), "Logger loot header widths must be applied centrally")
assert(logger:find("applyLootRowColumnWidths", 1, true), "Logger loot row widths must be applied centrally")
assert(logger:find("applyAttendanceListColumnWidths", 1, true), "Logger attendance header widths must be applied centrally")
assert(logger:find("applyAttendanceRowColumnWidths", 1, true), "Logger attendance row widths must be applied centrally")
assert(logger:find("applyBossListColumnWidths", 1, true), "Logger boss header widths must be applied centrally")
assert(logger:find("applyBossRowColumnWidths", 1, true), "Logger boss row widths must be applied centrally")
assert(logger:find("LOGGER_LOOT_ROW_HEIGHT", 1, true), "Logger loot row height must be explicit")
assert(logger:find("LOGGER_COMPACT_ROW_HEIGHT", 1, true), "Logger compact row height must be explicit")
assert(logger:find("RAID_INSPECT_SLOTS", 1, true), "Logger must define inspect item slot order")
assert(logger:find("renderAttendanceInspectIcons", 1, true), "Logger must render inspect icons in attendance rows")
assert(logger:find("setAttendanceSpecIcon(", 1, true), "Logger must render attendance spec icons through setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.specIcon", 1, true), "Logger must pass primary spec icon to setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.secondarySpecIcon", 1, true), "Logger must pass secondary spec icon to setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.specName", 1, true), "Logger must pass primary spec name to setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.secondarySpecName", 1, true), "Logger must pass secondary spec name to setAttendanceSpecIcon")
assert(logger:find("_krtAttendanceSecondarySpecIcon", 1, true), "Logger must keep a secondary spec icon cache/slot")
assert(logger:find("bindAttendanceSpecIconTooltip", 1, true), "Logger must bind spec icon tooltip behavior through a dedicated helper")
assert(logger:find('SetScript("OnEnter", function', 1, true), "Logger must bind hover tooltip handlers for spec icons")
assert(logger:find("GameTooltip:AddLine", 1, true), "Logger must add tooltip lines for spec icon hover")
assert(logger:find("icon._krtSpecName", 1, true), "Logger must cache spec name state on spec icon widgets")
assert(logger:find("setAttendanceSpecIconTexture(primaryIcon, primarySpecIcon, primarySpecName, false)", 1, true), "Logger must keep primary spec saturated")
assert(logger:find("setAttendanceSpecIconTexture(secondaryIcon, secondarySpecIcon, secondarySpecName, true)", 1, true), "Logger must desaturate secondary spec icon")
assert(logger:find("Services.EquipInspect", 1, true), "Logger must bind to EquipInspect service for manual force")
assert(logger:find("InternalEvents.EquipInspectUpdated", 1, true), "Logger must refresh from EquipInspectUpdated events")
assert(not logger:find("Services.RaidInspect", 1, true), "Logger must not reference retired RaidInspect service")
assert(not logger:find("InternalEvents.RaidInspectUpdated", 1, true), "Logger must not reference retired RaidInspect update event")
assert(logger:find("ToggleLootHistory", 1, true), "Logger must expose a dedicated Loot History opener")
assert(logger:find("ToggleRaidAttendance", 1, true), "Logger must expose a dedicated Raid Attendance opener")
assert(logger:find("KRTRaidAttendanceRaids", 1, true), "Logger must bind a separate Raid Attendance raids panel")
assert(logger:find("KRTRaidAttendanceRaidAttendees", 1, true), "Logger must bind a separate Raid Attendance attendees panel")
assert(logger:find("KRTRaidAttendanceBosses", 1, true), "Logger must bind a separate Raid Attendance boss participation panel")
assert(visuals:find("function Rows.SetLoggerRowIndex", 1, true), "Logger row striping must live in shared row visuals")
assert(visuals:find("function Rows.ApplyLoggerSkin", 1, true), "Logger panel skin must live in shared row visuals")
assert(visuals:find("function Rows.DrawMasterRollRow", 1, true), "Master roll row rendering must live in shared row visuals")
assert(logger:find("Rows.SetLoggerRowIndex(row, visibleIndex)", 1, true), "Logger row striping must use visible list position")
assert(logger:find("Rows.ApplyLoggerSkin(module._loggerPanelNames)", 1, true), "Logger controller must apply shared Logger skin")
assert(logger:find("rightInset = 0", 1, true), "Logger lists must keep the existing scrollbar inset policy")
assert(logger:find("setPanelVisible(refs.bossAttendees, false)", 1, true), "Logger refresh must keep the boss attendee panel hidden")
assert(frames:find("function Tooltips.ShowLines", 1, true), "Reusable multiline tooltip rendering must live in shared UI tooltips")
assert(logger:find("UI.Tooltips.ShowLines", 1, true), "Logger source-column tooltips must render through shared UI.Tooltips")
assert(not logger:find("GameTooltip:AddLine(L.StrLoggerSharedSource", 1, true), "Logger must not render shared source tooltip lines directly")

assert(loggerXml:find('Frame name="KRTRaidAttendance"', 1, true), "Logger XML must define a distinct Raid Attendance frame")
assert(loggerXml:find('Frame name="KRTRaidAttendanceRaids"', 1, true), "Raid Attendance XML must define a separate raids list")
assert(loggerXml:find('Frame name="KRTRaidAttendanceRaidAttendees"', 1, true), "Raid Attendance XML must define a separate attendees list")
assert(loggerXml:find('Frame name="KRTRaidAttendanceBosses"', 1, true), "Raid Attendance XML must define a separate boss participation list")
assert(loggerXml:find("$parentHeaderIlvl", 1, true), "Attendance XML must include iLvl header")
assert(loggerXml:find("$parentHeaderSpec", 1, true), "Attendance XML must include spec header")
assert(loggerXml:find("$parentHeaderInspect", 1, true), "Attendance XML must include inspect header")
assert(loggerXml:find("$parentInspectStatus", 1, true), "Attendance XML must define inspect status field")

assert(visuals:find("isLoggerRow%(row%)", 1, false), "Logger row visuals must stay scoped to Logger rows")
assert(visuals:find("_krtLoggerBg", 1, true), "Logger row backgrounds must stay in shared row visuals")
assert(visuals:find("0%.08, 0%.52, 0%.10", 1, false), "Logger selected rows must remain green")
assert(listController:find("cfg.drawRow(row, it, i)", 1, true), "ListController must pass visible row position to drawers")
assert(listController:find("syncScrollChildWidth", 1, true), "ListController rows must span the current scroll frame width")

print("logger visual refresh source contract passed")
