local function read(path)
    local file = assert(io.open(path, "r"))
    local text = file:read("*a")
    file:close()
    return text
end

local logger = read("!KRT/Controllers/Logger.lua")
local loggerTemplateXml = read("!KRT/UI/Logger.xml")
local lootHistoryXml = read("!KRT/UI/LootHistory.xml")
local raidAttendanceXml = read("!KRT/UI/RaidAttendance.xml")
local loggerXml = loggerTemplateXml .. "\n" .. lootHistoryXml .. "\n" .. raidAttendanceXml
local frames = read("!KRT/Modules/UI/Frames.lua")
local visuals = read("!KRT/Modules/UI/Visuals.lua")
local listController = read("!KRT/Modules/UI/ListController.lua")

assert(logger:find("calculateLoggerColumnWidths", 1, true), "Logger column widths must be calculated dynamically")
assert(logger:find("getLoggerListContentWidth", 1, true), "Logger list widths must come from visible frame geometry")
assert(logger:find("getLoggerListColumnBudget", 1, true), "Logger column budgets must account for row offsets and gaps")
assert(logger:find("LOGGER_HEADER_COLUMN_GAP", 1, true), "Logger headers must account for visual row gaps")
assert(logger:find("setHeaderWidth", 1, true), "Logger header width application must be centralized")
assert(logger:find("positionLoggerHeaderColumns", 1, true), "Logger header columns must be positioned from row geometry")
assert(logger:find("LOGGER_HEADER_TOP_OFFSET", 1, true), "Logger header positioning must keep a centralized top offset")
assert(visuals:find("resolveLoggerHeaderTab", 1, true), "Logger headers must render visible tab chrome through shared visuals")
assert(visuals:find("HeaderIlvl", 1, true), "Logger attendance headers must include ilvl for visual styling")
assert(visuals:find("HeaderSpec", 1, true), "Logger attendance headers must include spec for visual styling")
assert(visuals:find("HeaderInspect", 1, true), "Logger attendance headers must include inspect for visual styling")
assert(visuals:find("_krtHeaderTop", 1, true), "Logger header tabs must include a visible top edge")
assert(visuals:find("_krtHeaderBottom", 1, true), "Logger header tabs must include a visible bottom edge")
assert(logger:find("LOGGER_LOOT_COLUMN_MIN_WIDTHS", 1, true), "Logger loot column minimums must be centralized")
assert(logger:find("LOGGER_LOOT_COLUMN_RATIOS", 1, true), "Logger loot column ratios must be centralized")
assert(logger:find("LOGGER_ATTENDANCE_COLUMN_MIN_WIDTHS", 1, true), "Logger attendance column minimums must be centralized")
assert(logger:find("spec = 37", 1, true), "Logger attendance spec column minimum width must be 37")
assert(logger:find("inspect = 324", 1, true), "Logger attendance inspect column minimum width must be 324")
assert(logger:find("LOGGER_ATTENDANCE_TIME_COLUMN_MIN_WIDTH", 1, true), "Logger attendance time columns must have a readable minimum")
assert(logger:find("LOGGER_ATTENDANCE_COLUMN_RATIOS", 1, true), "Logger attendance column ratios must be centralized")
assert(logger:find("RAID_INSPECT_ICON_SIZE = 18", 1, true), "Logger raid inspect icons must be 18px")
assert(logger:find("RAID_SPEC_ICON_SIZE = 17", 1, true), "Logger raid spec icons must be 17px")
assert(logger:find("RAID_INSPECT_ICON_GAP = 1", 1, true), "Logger raid inspect icon gap must be 1px")
assert(logger:find("RAID_SPEC_ICON_GAP = 1", 1, true), "Logger raid spec icon gap must be 1px")
assert(logger:find("RAID_INSPECT_ICON_LEFT_OFFSET", 1, true), "Logger inspect icons must have a 1px left offset constant")
assert(loggerTemplateXml:find('Frame name="KRTLogPanelTemplate"', 1, true), "Shared log XML must define KRTLogPanelTemplate")
assert(loggerTemplateXml:find('Button name="KRTLogTableHeaderTemplate"', 1, true), "Shared log XML must define KRTLogTableHeaderTemplate")
assert(loggerTemplateXml:find('Button name="KRTLogRaidRowTemplate"', 1, true), "Shared log XML must define KRTLogRaidRowTemplate")
assert(lootHistoryXml:find('Button name="KRTLootHistoryLootRowTemplate"', 1, true), "Loot History XML must define KRTLootHistoryLootRowTemplate")
assert(raidAttendanceXml:find('Button name="KRTRaidAttendancePlayerRowTemplate"', 1, true), "Raid Attendance XML must define KRTRaidAttendancePlayerRowTemplate")
assert(
    raidAttendanceXml:find('Button name="KRTRaidAttendanceInspectItemIconButtonTemplate"', 1, true),
    "Raid Attendance XML must define KRTRaidAttendanceInspectItemIconButtonTemplate"
)
assert(logger:find('rowTmpl = "KRTLogRaidRowTemplate"', 1, true), "Logger raid lists must use the shared log raid row template")
assert(logger:find('rowTmpl = "KRTLootHistoryLootRowTemplate"', 1, true), "Loot History loot list must use the Loot History row template")
assert(logger:find('rowTmpl = "KRTRaidAttendancePlayerRowTemplate"', 1, true), "Raid Attendance players list must use the Raid Attendance row template")
assert(logger:find('ROLLTYPE_PICKER_FRAME = "KRTLootHistoryRollTypePickerFrame"', 1, true), "Loot History roll type picker must use the semantic frame name")
assert(logger:find('"KRTLootHistoryItemMenuFrame"', 1, true), "Loot History item menu must use the semantic frame name")
assert(not logger:find('rowTmpl = "KRTLoggerRaidButton"', 1, true), "Logger Lua must not keep KRTLoggerRaidButton row template")
assert(not logger:find('rowTmpl = "KRTLoggerLootButton"', 1, true), "Logger Lua must not keep KRTLoggerLootButton row template")
assert(not logger:find('rowTmpl = "KRTLoggerRaidAttendeeButton"', 1, true), "Logger Lua must not keep KRTLoggerRaidAttendeeButton row template")
assert(not logger:find('ROLLTYPE_PICKER_FRAME = "KRTLoggerRollTypePickerFrame"', 1, true), "Logger Lua must not keep KRTLoggerRollTypePickerFrame")
assert(not loggerXml:find("KRTLoggerFrameTemplate", 1, true), "Split XML must not keep KRTLoggerFrameTemplate")
assert(not loggerXml:find("KRTLoggerTableHeader", 1, true), "Split XML must not keep KRTLoggerTableHeader")
assert(not loggerXml:find("KRTLoggerRaidButton", 1, true), "Split XML must not keep KRTLoggerRaidButton")
assert(not loggerXml:find("KRTLoggerLootButton", 1, true), "Split XML must not keep KRTLoggerLootButton")
assert(not loggerXml:find("KRTLoggerRaidAttendeeButton", 1, true), "Split XML must not keep KRTLoggerRaidAttendeeButton")
assert(not loggerXml:find("KRTLoggerInspectItemIconButtonTemplate", 1, true), "Split XML must not keep KRTLoggerInspectItemIconButtonTemplate")
assert(not loggerXml:find("KRTLoggerRollTypePickerFrame", 1, true), "Split XML must not keep KRTLoggerRollTypePickerFrame")
assert(not logger:find("KRTLoggerItemMenuFrame", 1, true), "Logger Lua must not keep KRTLoggerItemMenuFrame")
assert(not logger:find('CreateFrame("Button", nil, row)', 1, true), "Logger must not create anonymous attendance icons in Lua")
assert(not logger:find('CreateFrame("Button", iconName, row', 1, true), "Logger must not create named attendance icon fallback buttons in Lua")
assert(not logger:find('icon:CreateTexture(nil, "ARTWORK")', 1, true), "Logger must not create icon textures in Lua when XML templates are used")
assert(logger:find("LOGGER_RAID_COLUMN_MIN_WIDTHS", 1, true), "Logger raid column minimums must be centralized")
assert(logger:find("LOGGER_RAID_COLUMN_RATIOS", 1, true), "Logger raid column ratios must be centralized")
assert(logger:find("applyLootListColumnWidths", 1, true), "Logger loot header widths must be applied centrally")
assert(logger:find("applyLootRowColumnWidths", 1, true), "Logger loot row widths must be applied centrally")
assert(logger:find("applyAttendanceListColumnWidths", 1, true), "Logger attendance header widths must be applied centrally")
assert(logger:find("applyAttendanceRowColumnWidths", 1, true), "Logger attendance row widths must be applied centrally")
assert(logger:find("LOGGER_LOOT_ROW_HEIGHT", 1, true), "Logger loot row height must be explicit")
assert(logger:find("LOGGER_COMPACT_ROW_HEIGHT", 1, true), "Logger compact row height must be explicit")
assert(logger:find("RAID_INSPECT_SLOTS", 1, true), "Logger must define inspect item slot order")
assert(logger:find("renderAttendanceInspectIcons", 1, true), "Logger must render inspect icons in attendance rows")
assert(logger:find("setAttendanceSpecIcon(", 1, true), "Logger must render attendance spec icons through setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.specIcon", 1, true), "Logger must pass primary spec icon to setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.secondarySpecIcon", 1, true), "Logger must pass secondary spec icon to setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.specName", 1, true), "Logger must pass primary spec name to setAttendanceSpecIcon")
assert(logger:find("it.inspect and it.inspect.secondarySpecName", 1, true), "Logger must pass secondary spec name to setAttendanceSpecIcon")
assert(logger:find("_krtAttendanceSecondarySpecIcon", 1, true), "Logger must keep a secondary spec icon cache/slot")
assert(logger:find("bindAttendanceSpecIconTooltip", 1, true), "Logger must bind spec icon tooltip behavior through a dedicated helper")
assert(logger:find('Frames.SetScriptSafely(icon, "OnEnter", function', 1, true), "Logger must bind hover tooltip handlers for spec icons")
assert(logger:find("GameTooltip:AddLine", 1, true), "Logger must add tooltip lines for spec icon hover")
assert(logger:find("icon._krtSpecName", 1, true), "Logger must cache spec name state on spec icon widgets")
assert(logger:find("setAttendanceSpecIconTexture(primaryIcon, primarySpecIcon, primarySpecName, false)", 1, true), "Logger must keep primary spec saturated")
assert(logger:find("setAttendanceSpecIconTexture(secondaryIcon, secondarySpecIcon, secondarySpecName, true)", 1, true), "Logger must desaturate secondary spec icon")
assert(logger:find("Services.EquipInspect", 1, true), "Logger must bind to EquipInspect service for manual force")
assert(logger:find("InternalEvents.EquipInspectUpdated", 1, true), "Logger must refresh from EquipInspectUpdated events")
assert(not logger:find("Services.RaidInspect", 1, true), "Logger must not reference retired RaidInspect service")
assert(not logger:find("InternalEvents.RaidInspectUpdated", 1, true), "Logger must not reference retired RaidInspect update event")
assert(logger:find("ToggleLootHistory", 1, true), "Logger must expose a dedicated Loot History opener")
assert(logger:find("ToggleRaidAttendance", 1, true), "Logger must expose a dedicated Raid Attendance opener")
assert(raidAttendanceXml:find("$parentInspectItemIcon1", 1, true), "Raid Attendance XML must define inspect item icon 1")
assert(raidAttendanceXml:find("$parentInspectItemIcon17", 1, true), "Raid Attendance XML must define inspect item icon 17")
assert(logger:find('makeModuleFrameGetter(module, "KRTLootHistory")', 1, true), "Loot History must bind the KRTLootHistory XML frame")
assert(not logger:find('makeModuleFrameGetter(module, "KRTLogger")', 1, true), "Loot History must not bind the legacy KRTLogger XML frame")
assert(loggerXml:find('Frame name="KRTLootHistory"', 1, true), "Logger XML must define the Loot History frame as KRTLootHistory")
assert(loggerXml:find('Frame name="KRTLootHistoryRaids"', 1, true), "Loot History XML must define a KRTLootHistory raids list")
assert(loggerXml:find('Frame name="KRTLootHistoryLoot"', 1, true), "Loot History XML must define a KRTLootHistory loot list")
assert(not loggerXml:find('Frame name="KRTLogger"', 1, true), "Loot History XML must not keep the legacy KRTLogger root frame")
assert(logger:find('UI.Frames.Get("KRTExportFrame")', 1, true), "Logger export must bind the KRTExportFrame XML frame")
assert(loggerXml:find('Frame name="KRTExportFrame"', 1, true), "Logger XML must define the export popup as KRTExportFrame")
assert(loggerXml:find('EditBox name="KRTExportFrameOutput"', 1, true), "Logger export XML must name the output editbox after KRTExportFrame")
assert(not loggerXml:find('Frame name="KRTLoggerExportFrame"', 1, true), "Logger XML must not keep the legacy KRTLoggerExportFrame popup")
assert(logger:find("KRTRaidAttendanceRaids", 1, true), "Logger must bind a separate Raid Attendance raids panel")
assert(logger:find("KRTRaidAttendanceRaidAttendees", 1, true), "Logger must bind a separate Raid Attendance attendees panel")
assert(not logger:find("KRTRaidAttendanceBosses", 1, true), "Logger must not keep a separate Raid Attendance boss participation panel")
assert(visuals:find("function Rows.SetLoggerRowIndex", 1, true), "Logger row striping must live in shared row visuals")
assert(visuals:find("function Rows.ApplyLoggerSkin", 1, true), "Logger panel skin must live in shared row visuals")
assert(visuals:find("function Rows.DrawMasterRollRow", 1, true), "Master roll row rendering must live in shared row visuals")
assert(logger:find("Rows.SetLoggerRowIndex(row, visibleIndex)", 1, true), "Logger row striping must use visible list position")
assert(logger:find("Rows.ApplyLoggerSkin(module._loggerPanelNames)", 1, true), "Logger controller must apply shared Logger skin")
assert(logger:find("rightInset = 0", 1, true), "Logger lists must keep the existing scrollbar inset policy")
assert(frames:find("function Tooltips.ShowLines", 1, true), "Reusable multiline tooltip rendering must live in shared UI tooltips")
assert(logger:find("UI.Tooltips.ShowLines", 1, true), "Logger source-column tooltips must render through shared UI.Tooltips")
assert(not logger:find("GameTooltip:AddLine(L.StrLoggerSharedSource", 1, true), "Logger must not render shared source tooltip lines directly")

assert(loggerXml:find('Frame name="KRTRaidAttendance"', 1, true), "Logger XML must define a distinct Raid Attendance frame")
assert(loggerXml:find('Frame name="KRTRaidAttendanceRaids"', 1, true), "Raid Attendance XML must define a separate raids list")
assert(loggerXml:find('Frame name="KRTRaidAttendanceRaidAttendees"', 1, true), "Raid Attendance XML must define a separate attendees list")
assert(not loggerXml:find('Frame name="KRTRaidAttendanceBosses"', 1, true), "Raid Attendance XML must not define a boss participation list panel")
assert(loggerXml:find("$parentHeaderIlvl", 1, true), "Attendance XML must include iLvl header")
assert(loggerXml:find("$parentHeaderSpec", 1, true), "Attendance XML must include spec header")
assert(loggerXml:find("$parentHeaderInspect", 1, true), "Attendance XML must include inspect header")
assert(loggerXml:find("$parentInspectStatus", 1, true), "Attendance XML must define inspect status field")

assert(visuals:find("isLoggerRow%(row%)", 1, false), "Logger row visuals must stay scoped to Logger rows")
assert(visuals:find("_krtLoggerBg", 1, true), "Logger row backgrounds must stay in shared row visuals")
assert(visuals:find("0%.08, 0%.52, 0%.10", 1, false), "Logger selected rows must remain green")
assert(listController:find("cfg.drawRow(row, it, i)", 1, true), "ListController must pass visible row position to drawers")
assert(listController:find("syncScrollChildWidth", 1, true), "ListController rows must span the current scroll frame width")

print("logger visual refresh source contract passed")
