local function read(path)
    local file = assert(io.open(path, "r"))
    local text = file:read("*a")
    file:close()
    return text
end

local function assertContains(text, needle, message)
    assert(text:find(needle, 1, true), message or ("missing: " .. needle))
end

local function assertNotContains(text, needle, message)
    assert(not text:find(needle, 1, true), message or ("unexpected: " .. needle))
end

local function assertBefore(text, first, second, message)
    local firstIndex = text:find(first, 1, true)
    local secondIndex = text:find(second, 1, true)
    assert(firstIndex, "missing: " .. first)
    assert(secondIndex, "missing: " .. second)
    assert(firstIndex < secondIndex, message or (first .. " must appear before " .. second))
end

local uiReadme = read("!KRT/UI/README.md")
local commonXml = read("!KRT/UI/Templates/Common.xml")
local raidGridXml = read("!KRT/UI/RaidGrid.xml")
local loggerXml = read("!KRT/UI/Logger.xml")
local lootCounterXml = read("!KRT/UI/LootCounter.xml")
local reservesXml = read("!KRT/UI/ReservesTemplates.xml")
local krtXml = read("!KRT/KRT.xml")
local visuals = read("!KRT/Modules/UI/Visuals.lua")
local frames = read("!KRT/Modules/UI/Frames.lua")
local screenNotice = read("!KRT/Modules/UI/ScreenNotice.lua")
local raidGrid = read("!KRT/Widgets/RaidGrid.lua")
local lootCounter = read("!KRT/Widgets/LootCounter.lua")
local reservesUi = read("!KRT/Widgets/ReservesUI.lua")
local logger = read("!KRT/Controllers/Logger.lua")
local master = read("!KRT/Controllers/Master.lua")

assertContains(uiReadme, "XML owns fixed visual structure", "UI README must document XML ownership")
assertContains(uiReadme, "Lua owns runtime behavior", "UI README must document Lua ownership")
assertContains(uiReadme, "Do not put addon behavior in XML", "UI README must forbid XML scripts")
assertContains(frames, "function Frames.ResolveNamedPartsBySuffix", "Frames must expose suffix ref resolver")
assertContains(frames, 'cacheField = cacheField or "_krtRefs"', "resolver must use the existing cache default")
assertContains(frames, "_G[parentName .. suffix]", "resolver must resolve XML children by parent suffix")
assertContains(commonXml, "KRTSelectableRowButtonTemplate", "Common XML must define selectable row template")
assertContains(commonXml, "$parentSelectedTexture", "selectable rows must expose selected texture")
assertContains(commonXml, "$parentFocusTexture", "selectable rows must expose focus texture")
assertContains(commonXml, "$parentPushedTexture", "selectable rows must expose pushed texture")
assertContains(commonXml, 'KRTSelectPlayerTemplate" inherits="KRTSelectableRowButtonTemplate', "player select rows must inherit selectable visuals")
assertContains(visuals, "_krtVisualsResolved", "row visuals must cache XML/fallback resolution")
assertContains(visuals, "SelectedTexture", "row visuals must resolve XML selected texture")
assertContains(visuals, "FocusTexture", "row visuals must resolve XML focus texture")
assertContains(visuals, "PushedTexture", "row visuals must resolve XML pushed texture")
assertContains(loggerXml, "$parentFill", "logger headers must expose fill texture")
assertContains(loggerXml, "$parentTop", "logger headers must expose top edge")
assertContains(loggerXml, "$parentBottom", "logger headers must expose bottom edge")
assertContains(loggerXml, "$parentLeft", "logger headers must expose left edge")
assertContains(loggerXml, "$parentRight", "logger headers must expose right edge")
assertContains(loggerXml, "$parentLoggerBg", "logger rows must expose background texture")
assertContains(loggerXml, "$parentLoggerBottomLine", "logger rows must expose bottom line texture")
assertContains(loggerXml, "$parentSpecIcon", "raid attendance rows must expose primary spec icon")
assertContains(loggerXml, "KRTLoggerInspectItemIconButtonTemplate", "logger must provide inspect icon button template")
assertContains(visuals, '_G[rowName .. "LoggerBg"]', "logger row styling must resolve XML background")
assertContains(visuals, '_G[rowName .. "LoggerBottomLine"]', "logger row styling must resolve XML bottom line")
assertContains(logger, "KRTLoggerInspectItemIconButtonTemplate", "logger inspect icons must use XML template")
assertContains(logger, 'rowName .. "SpecIcon"', "logger spec icons must resolve XML children")
assertContains(krtXml, '<Include file="UI\\ScreenNotice.xml" />', "KRT.xml must include ScreenNotice XML")
assertContains(krtXml, '<Include file="UI\\RaidGrid.xml" />', "KRT.xml should include RaidGrid XML")
assertContains(screenNotice, "_G[FRAME_NAME]", "ScreenNotice must resolve XML frame by name")
assertContains(screenNotice, 'FRAME_NAME .. "TitleText"', "ScreenNotice must resolve XML title text")
assertContains(screenNotice, 'FRAME_NAME .. "DetailText"', "ScreenNotice must resolve XML detail text")
assertContains(screenNotice, 'CreateFrame("Frame", FRAME_NAME, UIParent)', "ScreenNotice must keep fallback creation")
assertContains(raidGrid, "KRTRaidGridButtonTemplate", "RaidGrid lua should reference KRTRaidGridButtonTemplate")
assertContains(raidGrid, "KRTRaidGridFrameIcon", "RaidGrid lua should resolve icon global")
assertContains(raidGrid, "KRTRaidGridFrameTitle", "RaidGrid lua should resolve title global")
assertContains(raidGrid, "KRTRaidGridFrameCount", "RaidGrid lua should resolve count global")
assertContains(raidGrid, "KRTRaidGridFrameDivider", "RaidGrid lua should resolve divider global")
assertContains(raidGrid, "KRTRaidGridFrameEmpty", "RaidGrid lua should resolve empty global")
assertContains(raidGrid, "KRTRaidGridFrameCloseButton", "RaidGrid lua should resolve close button global")
assertContains(commonXml, "KRTRaidGridButtonTemplate", "common xml should define RaidGrid button template")
assertContains(krtXml, '<Include file="UI\\RaidGrid.xml" />', "KRT.xml include raidgrid.xml")
assertContains(raidGrid, "KRTRaidGridButtonTemplate", "RaidGrid lua should use button template")
assertContains(raidGrid, "KRTRaidGridFrameIcon", "RaidGrid lua should include icon child reference")
assertContains(raidGrid, "KRTRaidGridFrameCloseButton", "RaidGrid lua should include close button reference")
assertContains(raidGrid, "createButtonFallback", "RaidGrid lua should still fallback construct buttons")
assertContains(raidGridXml, 'name="KRTRaidGridFrame"', "raidgrid frame should be named and use KRT dialog")
assertContains(raidGridXml, 'inherits="KRTDialogTemplate"', "raidgrid frame should inherit KRTDialogTemplate")
assertContains(raidGridXml, "$parentIcon", "raidgrid xml should define $parentIcon")
assertContains(raidGridXml, "$parentTitle", "raidgrid xml should define $parentTitle")
assertContains(raidGridXml, "$parentCount", "raidgrid xml should define $parentCount")
assertContains(raidGridXml, "$parentDivider", "raidgrid xml should define $parentDivider")
assertContains(raidGridXml, "$parentEmpty", "raidgrid xml should define $parentEmpty")
assertContains(raidGridXml, "$parentCloseButton", "raidgrid xml should define $parentCloseButton")
assertNotContains(raidGridXml, "<Scripts>", "raidgrid xml should have no inline scripts")
assertNotContains(raidGridXml, "<On", "raidgrid xml should have no inline On handlers")
assertContains(commonXml, "$parentBg", "common xml should define button bg child")
assertContains(commonXml, "$parentTopLine", "common xml should define button top line child")
assertContains(commonXml, "$parentBottomLine", "common xml should define button bottom line child")
assertContains(commonXml, "$parentHighlight", "common xml should define button highlight child")
assertContains(commonXml, "$parentText", "common xml should define button text child")
assertContains(commonXml, "$parentSpecIcon", "common xml should define button spec icon child")
assertContains(raidGrid, '_G[buttonName .. "Text"]', "raidgrid lua should resolve text child from XML name")
assertContains(raidGrid, '_G[buttonName .. "SpecIcon"]', "raidgrid lua should resolve spec icon child from XML name")
assertContains(raidGrid, "_G.KRTRaidGridFrame or", "raidgrid lua should resolve frame from global or fallback")
assertContains(raidGrid, "KRTRaidGridFrameCloseButton", "raidgrid lua should resolve xml close button")
assertContains(raidGrid, 'SetScript", "OnEnter"', "raidgrid button should bind OnEnter in Lua")
assertContains(raidGrid, 'SetScript", "OnLeave"', "raidgrid button should bind OnLeave in Lua")
assertContains(raidGrid, 'SetScript", "OnClick"', "raidgrid button should bind OnClick in Lua")
assertContains(raidGrid, 'SetScript", "OnDragStart"', "raidgrid frame should bind drag start script")
assertContains(raidGrid, 'SetScript", "OnDragStop"', "raidgrid frame should bind drag stop script")
assertContains(raidGrid, "Services.SpecInspect:GetPlayerSpecSnapshot", "raidgrid should read spec snapshots")
assertContains(raidGrid, "SpecInspectUpdated", "raidgrid should refresh on spec updates")
assertContains(lootCounterXml, "KRTLootCounterHeaderTemplate", "loot counter header template must be defined in XML")
assertContains(lootCounterXml, "KRTLootCounterSectionTemplate", "loot counter section template must be defined in XML")
assertContains(lootCounterXml, "KRTLootCounterRowTemplate", "loot counter row template must be defined in XML")
assertContains(lootCounterXml, "$parentHeader", "loot counter scroll child must expose header suffix")
assertContains(lootCounter, "ensureHeaderFallback", "loot counter should keep header fallback")
assertContains(lootCounter, "ensureRowFallback", "loot counter should keep row fallback")
assertContains(lootCounter, "KRTLootCounterRow", "loot counter should use XML row template")
assertContains(lootCounterXml, "<ScrollChild>", "loot counter scroll frame should define XML scroll child")
assertContains(lootCounterXml, 'name="$parentScrollChild"', "loot counter scroll frame must name scroll child")
assertContains(lootCounterXml, 'name="$parentHeader" inherits="KRTLootCounterHeaderTemplate"', "loot counter header should be XML template instance")
assertContains(lootCounterXml, 'name="$parentMSSection" inherits="KRTLootCounterSectionTemplate"', "loot counter MS section should be XML template instance")
assertContains(lootCounterXml, 'name="$parentOSSection" inherits="KRTLootCounterSectionTemplate"', "loot counter OS section should be XML template instance")
assertContains(lootCounterXml, 'name="$parentFreeSection" inherits="KRTLootCounterSectionTemplate"', "loot counter FREE section should be XML template instance")
assertContains(lootCounter, "scrollChild:GetName()", "loot counter should derive parent child names from scroll child")
assertContains(lootCounter, 'CreateFrame("Frame", rowName, scrollChild, "KRTLootCounterRowTemplate")', "loot counter row should fallback to XML template")
assertContains(lootCounter, "row._initialized", "row initialization should be done once")
assertContains(lootCounter, "return ensureHeaderFallback()", "loot counter must preserve header fallback behavior")
assertContains(lootCounter, "return ensureRowFallback(i, rowHeight)", "loot counter must preserve row fallback behavior")
assertNotContains(lootCounterXml, "<Scripts>", "LootCounter XML must remain behavior-free")
assertNotContains(lootCounterXml, "<On", "LootCounter XML must not define inline event handlers")
assertContains(reservesXml, "$parentTopSeparator", "reserve rows must expose top separator")
assertContains(reservesXml, "$parentBottomSeparator", "reserve rows must expose bottom separator")
assertContains(reservesUi, "TopSeparator", "ReservesUI must resolve XML top separator")
assertContains(reservesUi, "BottomSeparator", "ReservesUI must resolve XML bottom separator")
assertContains(master, "KRTItemSelectionFrame", "Master must instantiate the dedicated item selection template")
assertNotContains(master, 'CreateFrame("Frame", nil, frame, "KRTDialogTemplate")', "Master must stop bypassing KRTItemSelectionFrame")

print("ui xml homogenization source contract passed")
