local function read(path)
    local file = assert(io.open(path, "r"))
    local text = file:read("*a")
    file:close()
    return text
end

local function assertContains(text, needle, message)
    assert(text:find(needle, 1, true), message or ("missing: " .. needle))
end

local function assertNotContains(text, needle, message)
    assert(not text:find(needle, 1, true), message or ("unexpected: " .. needle))
end

local function assertBefore(text, first, second, message)
    local firstIndex = text:find(first, 1, true)
    local secondIndex = text:find(second, 1, true)
    assert(firstIndex, "missing: " .. first)
    assert(secondIndex, "missing: " .. second)
    assert(firstIndex < secondIndex, message or (first .. " must appear before " .. second))
end

local uiReadme = read("!KRT/UI/README.md")
local commonXml = read("!KRT/UI/Templates/Common.xml")
local raidGridXml = read("!KRT/UI/RaidGrid.xml")
local loggerTemplateXml = read("!KRT/UI/Logger.xml")
local lootHistoryXml = read("!KRT/UI/LootHistory.xml")
local raidAttendanceXml = read("!KRT/UI/RaidAttendance.xml")
local loggerXml = loggerTemplateXml .. "\n" .. lootHistoryXml .. "\n" .. raidAttendanceXml
local lootCounterXml = read("!KRT/UI/LootCounter.xml")
local warningsXml = read("!KRT/UI/Warnings.xml")
local reservesXml = read("!KRT/UI/Reserves.xml")
local toc = read("!KRT/!KRT.toc")
local visuals = read("!KRT/Modules/UI/Visuals.lua")
local frames = read("!KRT/Modules/UI/Frames.lua")
local screenNotice = read("!KRT/Modules/UI/ScreenNotice.lua")
local raidGrid = read("!KRT/Widgets/RaidGrid.lua")
local lootCounter = read("!KRT/Widgets/LootCounter.lua")
local reservesUi = read("!KRT/Widgets/ReservesUI.lua")
local logger = read("!KRT/Controllers/Logger.lua")
local master = read("!KRT/Controllers/Master.lua")

assertContains(uiReadme, "XML owns fixed visual structure", "UI README must document XML ownership")
assertContains(uiReadme, "Lua owns runtime behavior", "UI README must document Lua ownership")
assertContains(uiReadme, "Do not put addon behavior in XML", "UI README must forbid XML scripts")
assertContains(frames, "function Frames.ResolveNamedPartsBySuffix", "Frames must expose suffix ref resolver")
assertContains(frames, 'cacheField = cacheField or "_krtRefs"', "resolver must use the existing cache default")
assertContains(frames, "_G[parentName .. suffix]", "resolver must resolve XML children by parent suffix")
assertContains(commonXml, "KRTSelectableRowButtonTemplate", "Common XML must define selectable row template")
assertContains(commonXml, "$parentSelectedTexture", "selectable rows must expose selected texture")
assertContains(commonXml, "$parentFocusTexture", "selectable rows must expose focus texture")
assertContains(commonXml, "$parentPushedTexture", "selectable rows must expose pushed texture")
assertContains(commonXml, 'KRTSelectPlayerTemplate" inherits="KRTSelectableRowButtonTemplate', "player select rows must inherit selectable visuals")
assertContains(visuals, "_krtVisualsResolved", "row visuals must cache XML/fallback resolution")
assertContains(visuals, "SelectedTexture", "row visuals must resolve XML selected texture")
assertContains(visuals, "FocusTexture", "row visuals must resolve XML focus texture")
assertContains(visuals, "resolveRowTextures", "row visuals must resolve XML row textures and apply runtime state")
assertNotContains(visuals, "Rows._fallbackStats", "row fallback stats should not be tracked in visual module")
assertNotContains(visuals, "Rows.GetFallbackStats", "row fallback stats getter should be removed")
assertNotContains(visuals, "row:CreateTexture", "row fallback textures should not be created in Lua")
assertContains(loggerXml, "$parentFill", "logger headers must expose fill texture")
assertContains(loggerXml, "$parentTop", "logger headers must expose top edge")
assertContains(loggerXml, "$parentBottom", "logger headers must expose bottom edge")
assertContains(loggerXml, "$parentLeft", "logger headers must expose left edge")
assertContains(loggerXml, "$parentRight", "logger headers must expose right edge")
assertContains(loggerXml, "$parentLoggerBg", "logger rows must expose background texture")
assertContains(loggerXml, "$parentLoggerBottomLine", "logger rows must expose bottom line texture")
assertContains(warningsXml, 'KRTWarningButtonTemplate" virtual="true" inherits="KRTSelectableRowButtonTemplate"', "warning rows should inherit selectable visuals template")
assertContains(loggerXml, "$parentSpecIcon", "raid attendance rows must expose primary spec icon")
assertNotContains(commonXml, "KRTLoggerInspectItemIconButtonTemplate", "common templates must not keep logger-prefixed inspect icon template")
assertContains(raidAttendanceXml, "KRTRaidAttendanceInspectItemIconButtonTemplate", "raid attendance xml must provide inspect icon button template")
assertNotContains(loggerXml, 'name="KRTLoggerInspectItemIconButtonTemplate"', "split logger xml must not keep logger-prefixed runtime icon template")
assertContains(visuals, '_G[rowName .. "LoggerBg"]', "logger row styling must resolve XML background")
assertContains(visuals, '_G[rowName .. "LoggerBottomLine"]', "logger row styling must resolve XML bottom line")
assertNotContains(visuals, "row:SetPushedTexture", "pushed texture fallback wiring should be removed from visuals module")
assertContains(visuals, "resolveLoggerHeaderTab", "logger headers should resolve XML tab parts without creating textures")
assertNotContains(visuals, "header:CreateTexture", "logger header fallback textures should not be created in Lua")
assertNotContains(visuals, "row._krtSpecIcon", "master spec icon fallback storage should be removed from visuals module")
assertContains(logger, 'local iconName = rowName and (rowName .. "InspectItemIcon"', "logger inspect icons must resolve XML globals")
assertContains(loggerXml, "$parentInspectItemIcon1", "logger xml must define first inspect item icon slot")
assertContains(loggerXml, "$parentInspectItemIcon17", "logger xml must define last inspect item icon slot")
assertContains(logger, '_G[iconName .. "Texture"]', "logger must resolve icon textures through XML globals")
assertContains(raidAttendanceXml, 'inherits="KRTRaidAttendanceInspectItemIconButtonTemplate"', "raid attendance inspect icon slots must inherit the semantic inspect icon template")
assertContains(logger, 'rowName .. "SpecIcon"', "logger spec icons must resolve XML children")
assertNotContains(logger, 'CreateFrame("Button", iconName, row', "logger inspect icon creation should resolve XML globals")
assertNotContains(logger, 'CreateFrame("Button", nil, row)', "logger icon creation should not create anonymous fallback buttons")
assertNotContains(logger, 'icon:CreateTexture(nil, "ARTWORK")', "logger icon textures should come from XML child globals")
assertContains(toc, "UI\\ScreenNotice.xml", "TOC must early-load ScreenNotice XML")
assertContains(toc, "UI\\RaidGrid.xml", "TOC must early-load RaidGrid XML")
assertBefore(toc, "UI\\Templates\\Common.xml", "UI\\ScreenNotice.xml", "common templates must load before ScreenNotice XML")
assertBefore(toc, "UI\\ScreenNotice.xml", "UI\\RaidGrid.xml", "ScreenNotice XML must keep requested TOC order")
assertNotContains(toc, "KRT.xml", "TOC must load concrete XML files directly")
assertContains(toc, "UI\\Logger.xml", "TOC must load shared Logger UI templates")
assertContains(toc, "UI\\LootHistory.xml", "TOC must load Loot History XML")
assertContains(toc, "UI\\RaidAttendance.xml", "TOC must load Raid Attendance XML")
assertBefore(toc, "UI\\Logger.xml", "UI\\LootHistory.xml", "shared Logger templates must load before Loot History XML")
assertBefore(toc, "UI\\Logger.xml", "UI\\RaidAttendance.xml", "shared Logger templates must load before Raid Attendance XML")
assertBefore(toc, "UI\\LootHistory.xml", "Controllers\\Logger.lua", "Loot History XML must load before Logger controller")
assertBefore(toc, "UI\\RaidAttendance.xml", "Controllers\\Logger.lua", "Raid Attendance XML must load before Logger controller")
assertContains(screenNotice, "_G[FRAME_NAME]", "ScreenNotice must resolve XML frame by name")
assertContains(screenNotice, 'FRAME_NAME .. "TitleText"', "ScreenNotice must resolve XML title text")
assertContains(screenNotice, 'FRAME_NAME .. "DetailText"', "ScreenNotice must resolve XML detail text")
assertNotContains(screenNotice, 'CreateFrame("Frame", FRAME_NAME, UIParent)', "ScreenNotice must rely on XML frame after in-game validation")
assertNotContains(screenNotice, 'frame:CreateFontString(nil, "OVERLAY")', "ScreenNotice must rely on XML fontstrings after in-game validation")
assertContains(raidGrid, "KRTRaidGridButtonTemplate", "RaidGrid lua should reference KRTRaidGridButtonTemplate")
assertContains(raidGrid, "KRTRaidGridFrameIcon", "RaidGrid lua should resolve icon global")
assertContains(raidGrid, "KRTRaidGridFrameTitle", "RaidGrid lua should resolve window title global")
assertContains(raidGrid, "KRTRaidGridFrameContextTitle", "RaidGrid lua should resolve context title global")
assertContains(raidGrid, "KRTRaidGridFrameCount", "RaidGrid lua should resolve count global")
assertContains(raidGrid, "KRTRaidGridFrameDivider", "RaidGrid lua should resolve divider global")
assertContains(raidGrid, "KRTRaidGridFrameEmpty", "RaidGrid lua should resolve empty global")
assertContains(raidGrid, "KRTRaidGridFrameCloseButton", "RaidGrid lua should resolve close button global")
assertContains(commonXml, "KRTRaidGridButtonTemplate", "common xml should define RaidGrid button template")
assertContains(toc, "UI\\RaidGrid.xml", "TOC should include raidgrid.xml")
assertContains(raidGrid, "KRTRaidGridButtonTemplate", "RaidGrid lua should use button template")
assertContains(raidGrid, "KRTRaidGridFrameIcon", "RaidGrid lua should include icon child reference")
assertContains(raidGrid, "KRTRaidGridFrameCloseButton", "RaidGrid lua should include close button reference")
assertNotContains(raidGrid, "createButtonFallback", "RaidGrid buttons must rely on XML templates after in-game validation")
assertNotContains(raidGrid, "local function ensureRegion()", "RaidGrid must not keep fake visual-region fallback helpers")
assertNotContains(raidGrid, "local function createTexture(parent, layer)", "RaidGrid must not create XML-owned textures in Lua")
assertNotContains(raidGrid, "local function createFontString(parent, template)", "RaidGrid must not create XML-owned fontstrings in Lua")
assertContains(raidGridXml, 'name="KRTRaidGridFrame"', "raidgrid frame should be named")
assertNotContains(raidGridXml, 'inherits="KRTDialogTemplate"', "raidgrid frame should own its window chrome")
assertContains(raidGridXml, "Interface\\PaperDollInfoFrame\\UI-GearManager-Border", "raidgrid should use standard window border art")
assertContains(raidGridXml, "$parentIcon", "raidgrid xml should define $parentIcon")
assertContains(raidGridXml, "$parentTitle", "raidgrid xml should define $parentTitle")
assertContains(raidGridXml, "$parentContextTitle", "raidgrid xml should define $parentContextTitle")
assertContains(raidGridXml, "$parentCount", "raidgrid xml should define $parentCount")
assertContains(raidGrid, "Frames.SetFrameTitle", "RaidGrid lua should use shared frame title helper")
assertContains(raidGrid, "StrRaidGridSelectorTitle", "RaidGrid lua should localize selector title")
assertContains(raidGridXml, "$parentDivider", "raidgrid xml should define $parentDivider")
assertContains(raidGridXml, "$parentEmpty", "raidgrid xml should define $parentEmpty")
assertContains(raidGridXml, "$parentCloseButton", "raidgrid xml should define $parentCloseButton")
assertNotContains(raidGridXml, "<Scripts>", "raidgrid xml should have no inline scripts")
assertNotContains(raidGridXml, "<On", "raidgrid xml should have no inline On handlers")
assertContains(commonXml, "$parentBg", "common xml should define button bg child")
assertContains(commonXml, "$parentTopLine", "common xml should define button top line child")
assertContains(commonXml, "$parentBottomLine", "common xml should define button bottom line child")
assertContains(commonXml, "$parentHighlight", "common xml should define button highlight child")
assertContains(commonXml, "$parentText", "common xml should define button text child")
assertContains(commonXml, "$parentSpecIcon", "common xml should define button spec icon child")
assertContains(raidGrid, '_G[buttonName .. "Text"]', "raidgrid lua should resolve text child from XML name")
assertContains(raidGrid, '_G[buttonName .. "SpecIcon"]', "raidgrid lua should resolve spec icon child from XML name")
assertNotContains(raidGrid, "_G.KRTRaidGridFrame or", "RaidGrid frame must rely on XML top-level frame after in-game validation")
assertContains(raidGrid, "KRTRaidGridFrameCloseButton", "raidgrid lua should resolve xml close button")
assertContains(raidGrid, 'SetScript", "OnEnter"', "raidgrid button should bind OnEnter in Lua")
assertContains(raidGrid, 'SetScript", "OnLeave"', "raidgrid button should bind OnLeave in Lua")
assertContains(raidGrid, 'SetScript", "OnClick"', "raidgrid button should bind OnClick in Lua")
assertContains(raidGrid, 'SetScript", "OnDragStart"', "raidgrid frame should bind drag start script")
assertContains(raidGrid, 'SetScript", "OnDragStop"', "raidgrid frame should bind drag stop script")
assertContains(raidGrid, "Services.SpecInspect:GetPlayerSpecSnapshot", "raidgrid should read spec snapshots")
assertContains(raidGrid, "SpecInspectUpdated", "raidgrid should refresh on spec updates")
assertContains(reservesXml, "$parentTopSeparator", "reserve rows must expose top separator")
assertContains(reservesXml, "$parentBottomSeparator", "reserve rows must expose bottom separator")
assertContains(reservesUi, "TopSeparator", "ReservesUI must resolve XML top separator")
assertContains(reservesUi, "BottomSeparator", "ReservesUI must resolve XML bottom separator")
assertNotContains(reservesUi, 'local topSeparator = row:CreateTexture(nil, "BORDER")', "Reserves row top separator must rely on XML after in-game validation")
assertNotContains(reservesUi, 'local separator = row:CreateTexture(nil, "BORDER")', "Reserves row bottom separator must rely on XML after in-game validation")
assertContains(reservesXml, "$parentNameHotspot", "reserve rows must expose name tooltip hotspot")
assertContains(reservesXml, "$parentPlayersHotspot", "reserve rows must expose players tooltip hotspot")
assertContains(reservesUi, "NameHotspot", "ReservesUI must resolve name tooltip hotspot")
assertContains(reservesUi, "PlayersHotspot", "ReservesUI must resolve players tooltip hotspot")
assertNotContains(reservesUi, 'CreateFrame("Button", nil, row.textBlock)', "Reserves row hotspots should not be created from Lua")
assertContains(master, "KRTItemSelectionFrame", "Master must instantiate the dedicated item selection template")
assertContains(master, '"SpecIcon"', "Master roll rows should map SpecIcon in row parts")
assertNotContains(master, 'CreateFrame("Frame", nil, frame, "KRTDialogTemplate")', "Master must stop bypassing KRTItemSelectionFrame")

print("ui xml homogenization source contract passed")
