local _, addon = ...

addon.L = addon.L or {}
local L = addon.L

-- ==================== Log Messages ==================== --
L.LogCoreCallbackHandlerMissing   = "[Core] CallbackHandler missing: using fallback event wiring"
L.LogCoreLoaded                   = "[Core] Loaded version=%s logLevel=%s perfMode=%s"
L.LogCoreBuild                    = "[Core] build=%s"
L.LogCoreEventsRegistered         = "[Core] Events registered=%d"
L.LogCorePlayerEnteringWorld      = "[Core] PLAYER_ENTERING_WORLD -> scheduling FirstCheck"
L.LogRaidLeftGroupEndSession      = "[Raid] Left group -> ending current raid session"
L.LogRaidRosterUpdate             = "[Raid] RosterUpdate v=%d num=%d"
L.LogRaidCreated                  = "[Raid] Created id=%d zone=%s size=%d players=%d"
L.LogRaidEnded                    = "[Raid] Ended id=%d zone=%s size=%d bosses=%d loot=%d duration=%d"
L.LogRaidCheck                    = "[Raid] Check zone=%s diff=%s current=%s"
L.LogRaidSessionChange            = "[Raid] Session change zone=%s size=%d diff=%d"
L.LogRaidSessionCreate            = "[Raid] Session create zone=%s size=%d diff=%d"
L.LogRaidFirstCheck               = "[Raid] FirstCheck inGroup=%s currentRaid=%s instance=%s type=%s diff=%s"
L.LogRaidPlayerJoin               = "[Raid] Player join name=%s raidId=%d"
L.LogRaidPlayerRefresh            = "[Raid] Player refresh name=%s raidId=%d"
L.LogRaidInstanceWelcome          = "[Raid] RAID_INSTANCE_WELCOME name=%s type=%s diff=%s nextReset=%s"
L.LogRaidUnmappedZone             = "[Raid] Unmapped raid zone: %s (diff=%s) -> no session check"
L.LogRaidInstanceRecognized       = "[Raid] Instance recognized: %s diff=%s -> check"
L.LogBossAddSkipped               = "[Boss] AddBoss skipped raidId=%s boss=%s"
L.LogBossLogged                   = "[Boss] Logged boss=%s diff=%d raid=%d players=%d"
L.LogBossLastBossHash             = "[Boss] lastBoss=%d hash=%s"
L.LogBossNoContextTrash           = "[Boss] No boss context -> creating _TrashMob_ bucket"
L.LogBossYellMatched              = "[Boss] Yell matched text=%s boss=%s"
L.LogBossUnitDiedMatched          = "[Boss] UNIT_DIED matched npcId=%d boss=%s"
L.LogLootParseFailed              = "[Loot] Parse failed msg=%s"
L.LogLootParsed                   = "[Loot] Parsed looter=%s link=%s count=%d"
L.LogLootIgnoredBelowThreshold    = "[Loot] Ignored below threshold rarity=%s thr=%d link=%s"
L.LogLootIgnoredItemId            = "[Loot] Ignored itemId=%s link=%s (ignoredItems)"
L.LogLootLogged                   = "[Loot] Logged raidId=%d itemId=%s bossNum=%s looter=%s"
L.LogLootFetchStart               = "[Loot] FetchLoot numLootItems=%d oldIndex=%d"
L.LogLootFetchDone                = "[Loot] FetchLoot done lootCount=%d currentIndex=%d"
L.LogLootItemInfoMissing          = "[Loot] ItemInfo missing -> deferred link=%s"
L.LogLootChatMsgLootRaw           = "[Loot] CHAT_MSG_LOOT raw=%s"
L.LogMLCandidateCacheBuilt        = "[ML] Candidate cache built item=%s candidates=%d"
L.LogMLAwardRequested             = "[ML] Award requested winner=%s type=%d roll=%d item=%s"
L.LogMLItemLocked                 = "[ML] ITEM_LOCKED bag=%s slot=%s link=%s count=%s soulbound=%s"
L.LogMLInventorySoulbound         = "[ML] Inventory item is soulbound -> cannot trade link=%s"
L.LogMLLootOpenedTrace            = "[ML] LOOT_OPENED items=%d fromInv=%s"
L.LogMLLootOpenedInfo             = "[ML] Loot opened items=%d fromInv=%s target=%s"
L.LogMLLootClosed                 = "[ML] LOOT_CLOSED opened=%s items=%d"
L.LogMLLootClosedCleanup          = "[ML] LOOT_CLOSED -> scheduling cleanup"
L.LogMLLootSlotCleared            = "[ML] LOOT_SLOT_CLEARED items=%d"
L.LogMLLootWindowEmptied          = "[ML] Loot window emptied"
L.LogMLCandidateCacheMiss         = "[ML] Candidate cache miss item=%s player=%s -> rebuild"
L.LogMLAwarded                    = "[ML] Awarded item=%s -> %s type=%d roll=%d slot=%d cand=%d"
L.LogMLAwardLoggerFailed          = "[ML] Awarded but Logger failed raidId=%s itemIndex=%s link=%s"
L.LogTradeAcceptUpdate            = "[Trade] ACCEPT_UPDATE trader=%s winner=%s t=%s p=%s"
L.LogTradeCompleted               = "[Trade] Completed item=%s winner=%s type=%d roll=%d"
L.LogTradeLoggerLogFailed         = "[Trade] Logger log failed raidId=%s itemIndex=%s link=%s"
L.LogTradeKeepLoggerFailed        = "[Trade] Keep logged but Logger failed raidId=%s itemIndex=%s link=%s"
L.LogTradeStart                   = "[Trade] TradeItem start item=%s trader=%s target=%s type=%d roll=%d count=%d"
L.LogTradeTraderKeeps             = "[Trade] Trader keeps item=%s winner=%s"
L.LogTradeStackBlocked            = "[Trade] Stack trade blocked ignoreStacks=%s link=%s"
L.LogTradeInitiated               = "[Trade] Initiated item=%s -> %s"
L.LogTradeDelayedOutOfRange       = "[Trade] Delayed: %s out of range item=%s"
L.LogSRImportRequested            = "[SR] Import requested chars=%d"
L.LogSRItemInfoResolved           = "[SR] Item info resolved itemId=%d link=%s"
L.LogSRParseSkippedLine           = "[SR] ParseCSV skipped line=%s"
L.LogSRImportComplete             = "[SR] Import complete players=%d"
L.LogSRQueryMissingItems          = "[SR] QueryMissingItems updated=%s pending=%d"
L.LogLoggerLootLogAttempt         = "[Logger] Loot:Log attempt source=%s raidId=%s itemIndex=%s "
    .. "looter=%s type=%s roll=%s lastBoss=%s"
L.LogLoggerNoRaidSession          = "[Logger] Loot:Log FAILED no raid session raidId=%s itemIndex=%s"
L.LogLoggerItemNotFound           = "[Logger] Loot:Log FAILED item not found raidId=%d itemIndex=%s lootCount=%d"
L.LogLoggerLooterEmpty            = "[Logger] Loot:Log looter empty raidId=%d itemIndex=%s link=%s"
L.LogLoggerRollTypeNil            = "[Logger] Loot:Log rollType nil raidId=%d itemIndex=%s looter=%s"
L.LogLoggerLootBefore             = "[Logger] Loot:Log BEFORE raidId=%d itemIndex=%s link=%s "
    .. "prevLooter=%s prevType=%s prevRoll=%s"
L.LogLoggerLootOverwrite          = "[Logger] Loot overwrite raidId=%d itemIndex=%s link=%s from=%s to=%s"
L.LogLoggerLootRecorded           = "[Logger] Loot recorded source=%s raidId=%d itemIndex=%s link=%s -> "
    .. "looter=%s type=%s roll=%s"
L.LogLoggerVerifyFailed           = "[Logger] Loot:Log VERIFY FAILED raidId=%d itemIndex=%s "
    .. "got(looter=%s type=%s roll=%s)"
L.LogLoggerVerified               = "[Logger] Loot:Log verified raidId=%d itemIndex=%s"
L.LogLoggerRecordedNoBossContext  = "[Logger] Loot recorded without boss context raidId=%d itemIndex=%s link=%s"
L.LogLoggerBossLootRemoved        = "[Logger] Boss delete removed loot raidId=%d bossId=%d removed=%d"
