local _, addon                    = ...

addon.E                           = addon.E or {}
local E                           = addon.E

-- ==================== Log Messages ==================== --
E.LogCoreCallbackHandlerMissing   = "[Core] CallbackHandler missing: using fallback event wiring"
E.LogCoreLoaded                   = "[Core] Loaded version=%s logLevel=%s perfMode=%s"
E.LogCoreEventsRegistered         = "[Core] Events registered=%d"
E.LogCorePlayerEnteringWorld      = "[Core] PLAYER_ENTERING_WORLD -> scheduling FirstCheck"
E.LogRaidLeftGroupEndSession      = "[Raid] Left group -> ending current raid session"
E.LogRaidRosterUpdate             = "[Raid] RosterUpdate v=%d num=%d"
E.ErrLoggerUpdateRosterNotInRaid  = "[Logger] Cannot update roster: you are not in a raid."
E.ErrLoggerUpdateRosterNotCurrent = "[Logger] Cannot update roster: selected raid is not the current raid."
E.LogRaidCreated                  = "[Raid] Created id=%d zone=%s size=%d players=%d"
E.LogRaidEnded                    = "[Raid] Ended id=%d zone=%s size=%d bosses=%d loot=%d duration=%d"
E.LogRaidCheck                    = "[Raid] Check zone=%s diff=%s current=%s"
E.LogRaidSessionChange            = "[Raid] Session change zone=%s size=%d diff=%d"
E.LogRaidSessionCreate            = "[Raid] Session create zone=%s size=%d diff=%d"
E.LogRaidFirstCheck               = "[Raid] FirstCheck inGroup=%s currentRaid=%s instance=%s type=%s diff=%s"
E.LogRaidPlayerJoin               = "[Raid] Player join name=%s raidId=%d"
E.LogRaidPlayerRefresh            = "[Raid] Player refresh name=%s raidId=%d"
E.LogRaidInstanceWelcome          = "[Raid] RAID_INSTANCE_WELCOME name=%s type=%s diff=%s nextReset=%s"
E.LogRaidUnmappedZone             = "[Raid] Unmapped raid zone: %s (diff=%s) -> no session check"
E.LogRaidInstanceRecognized       = "[Raid] Instance recognized: %s diff=%s -> check"
E.LogBossAddSkipped               = "[Boss] AddBoss skipped raidId=%s boss=%s"
E.LogBossLogged                   = "[Boss] Logged boss=%s diff=%d raid=%d players=%d"
E.LogBossLastBossHash             = "[Boss] lastBoss=%d hash=%s"
E.LogBossNoContextTrash           = "[Boss] No boss context -> creating _TrashMob_ bucket"
E.LogBossYellMatched              = "[Boss] Yell matched text=%s boss=%s"
E.LogBossUnitDiedMatched          = "[Boss] UNIT_DIED matched npcId=%d boss=%s"
E.LogCoreEventHandlerFailed       = "[Core] Event handler failed event=%s err=%s"
E.LogLootParseFailed              = "[Loot] Parse failed msg=%s"
E.LogLootParsed                   = "[Loot] Parsed looter=%s link=%s count=%d"
E.LogLootIgnoredBelowThreshold    = "[Loot] Ignored below threshold rarity=%s thr=%d link=%s"
E.LogLootIgnoredItemId            = "[Loot] Ignored itemId=%s link=%s (ignoredItems)"
E.LogLootLogged                   = "[Loot] Logged raidId=%d itemId=%s bossNid=%s looter=%s"
E.LogLootFetchStart               = "[Loot] FetchLoot numLootItems=%d oldIndex=%d"
E.LogLootFetchDone                = "[Loot] FetchLoot done lootCount=%d currentIndex=%d"
E.LogLootItemInfoMissing          = "[Loot] ItemInfo missing -> deferred link=%s"
E.LogLootChatMsgLootRaw           = "[Loot] CHAT_MSG_LOOT raw=%s"
E.LogMLCandidateCacheBuilt        = "[ML] Candidate cache built item=%s candidates=%d"
E.LogMLAwardRequested             = "[ML] Award requested winner=%s type=%d roll=%d item=%s"
E.LogMLCountdownActive            = "[ML] Countdown active: wait for it to finish before awarding"
E.LogMLAwardBlocked               = "[ML] Award blocked lootCount=%d rollsCount=%d"
E.LogMLItemLocked                 = "[ML] ITEM_LOCKED bag=%s slot=%s link=%s count=%s soulbound=%s"
E.LogMLInventorySoulbound         = "[ML] Inventory item is soulbound -> cannot trade link=%s"
E.LogMLLootOpenedTrace            = "[ML] LOOT_OPENED items=%d fromInv=%s"
E.LogMLLootOpenedInfo             = "[ML] Loot opened items=%d fromInv=%s target=%s"
E.LogMLLootClosed                 = "[ML] LOOT_CLOSED opened=%s items=%d"
E.LogMLLootClosedCleanup          = "[ML] LOOT_CLOSED -> scheduling cleanup"
E.LogMLLootSlotCleared            = "[ML] LOOT_SLOT_CLEARED items=%d"
E.LogMLLootWindowEmptied          = "[ML] Loot window emptied"
E.LogMLCandidateCacheMiss         = "[ML] Candidate cache miss item=%s player=%s -> rebuild"
E.LogMLAwarded                    = "[ML] Awarded item=%s -> %s type=%d roll=%d slot=%d cand=%d"
E.LogMLAwardLoggerFailed          = "[ML] Awarded but Logger failed raidId=%s lootNid=%s link=%s"
E.ErrMLMultiAwardInProgress       = "[ML] Multi-award in progress: wait until it finishes before awarding again."
E.ErrMLMultiSelectTooMany         = "[ML] Cannot select more than %d winner(s) for this item."
E.ErrMLMultiSelectNotEnough       = "[ML] Select %d winner(s) before awarding multiple copies (currently %d)."
E.LogTradeAcceptUpdate            = "[Trade] ACCEPT_UPDATE trader=%s winner=%s t=%s p=%s"
E.LogTradeCompleted               = "[Trade] Completed item=%s winner=%s type=%d roll=%d"
E.LogTradeCurrentRollItemMissing  = "[Trade] currentRollItem missing; cannot update loot entry"
E.LogTradeLoggerLogFailed         = "[Trade] Logger log failed raidId=%s lootNid=%s link=%s"
E.LogTradeKeepLoggerFailed        = "[Trade] Keep logged but Logger failed raidId=%s lootNid=%s link=%s"
E.LogTradeStart                   = "[Trade] TradeItem start item=%s trader=%s target=%s type=%d roll=%d count=%d"
E.LogTradeTraderKeeps             = "[Trade] Trader keeps item=%s winner=%s"
E.LogTradeStackBlocked            = "[Trade] Stack trade blocked ignoreStacks=%s link=%s"
E.LogTradeInitiated               = "[Trade] Initiated item=%s -> %s"
E.LogTradeDelayedOutOfRange       = "[Trade] Delayed: %s out of range item=%s"
E.LogSRImportRequested            = "[SR] Import requested chars=%d"
E.LogSRItemInfoResolved           = "[SR] Item info resolved itemId=%d link=%s"
E.LogSRParseSkippedLine           = "[SR] ParseCSV skipped line=%s"
E.LogSRImportComplete             = "[SR] Import complete players=%d"
E.LogSRQueryMissingItems          = "[SR] QueryMissingItems updated=%s pending=%d"
E.LogRollsSortNoEntries           = "[Rolls] Sort skipped: no entries"
E.LogRollsAddEntry                = "[Rolls] Add name=%s roll=%d item=%s"
E.LogRollsBlockedPlayer           = "[Rolls] Blocked player=%s (%d/%d)"
E.LogRollsPlayerRolled            = "[Rolls] Player=%s item=%d"
E.LogRollsRecordState             = "[Rolls] Record=%s"
E.LogRollsCountdownBlocked        = "[Rolls] Blocked: countdown active"
E.LogRollsMissingItem             = "[Rolls] Item ID missing or loot table not ready - roll ignored"
E.LogRollsDeniedPlayer            = "[Rolls] Denied player=%s (%d/%d)"
E.LogRollsAcceptedPlayer          = "[Rolls] Accepted player=%s (%d/%d)"
E.LogRollsCurrentItemId           = "[Rolls] Current itemId=%s"
E.LogReservesTrackPending         = "[Reserves] Track pending itemId=%d pending=%d"
E.LogReservesItemReady            = "[Reserves] Item ready itemId=%d pending=%d"
E.LogReservesPendingComplete      = "[Reserves] Pending item info complete"
E.LogReservesToggleCollapse       = "[Reserves] Toggle collapse source=%s state=%s"
E.LogReservesSaveEntries          = "[Reserves] Save entries=%d"
E.LogReservesLoadData             = "[Reserves] Load data=%s"
E.LogReservesResetSaved           = "[Reserves] Reset saved data"
E.LogReservesFrameMissing         = "[Reserves] Reserve List frame not available"
E.LogReservesShowWindow           = "[Reserves] Show list window"
E.LogReservesHideWindow           = "[Reserves] Hide list window"
E.LogReservesOpenImportWindow     = "[Reserves] Open import window"
E.LogReservesImportWindowMissing  = "[Reserves] KRTImportWindow not found"
E.LogReservesFrameLoaded          = "[Reserves] Frame loaded"
E.LogReservesBindButton           = "[Reserves] Bind button=%s action=%s"
E.LogReservesItemInfoReceived     = "[Reserves] Item info received itemId=%d"
E.LogReservesUpdateItemData       = "[Reserves] Update item data %s"
E.LogReservesItemInfoMissing      = "[Reserves] Item info missing itemId=%d"
E.LogReservesItemInfoPending      = "[Reserves] Item info still pending itemId=%d"
E.LogReservesUILocalized          = "[Reserves] UI localized %s"
E.LogReservesUIAlreadyLocalized   = "[Reserves] UI already localized"
E.LogReservesPlayerFound          = "[Reserves] Player found %s data=%s"
E.LogReservesPlayerNotFound       = "[Reserves] Player not found %s"
E.LogReservesFetchAll             = "[Reserves] Fetch all players=%d"
E.LogReservesImportFailedEmpty    = "[Reserves] Import failed: empty or invalid data"
E.LogReservesParseStart           = "[Reserves] Parse CSV start"
E.LogReservesParseComplete        = "[Reserves] Parse CSV complete players=%d"
E.LogReservesQueryItemInfo        = "[Reserves] Query item info itemId=%d"
E.LogReservesItemInfoReady        = "[Reserves] Item info ready itemId=%d name=%s"
E.LogReservesItemInfoPendingQuery = "[Reserves] Item info pending itemId=%d"
E.LogReservesQueryMissingItems    = "[Reserves] Query missing items"
E.LogReservesMissingItems         = "[Reserves] Missing items requested=%d"
E.LogReservesCheckCount           = "[Reserves] Check count itemId=%d player=%s"
E.LogReservesFoundCount           = "[Reserves] Found itemId=%d player=%s qty=%d"
E.LogReservesNoCount              = "[Reserves] None itemId=%d player=%s"
E.LogReservesFormatPlayers        = "[Reserves] Format players itemId=%d"
E.LogReservesPlayersList          = "[Reserves] Players itemId=%d list=%s"
E.LogChangesInitTable             = "[Changes] Init table"
E.LogChangesFetchAll              = "[Changes] Fetch all"
E.LogLoggerLootLogAttempt         = "[Logger] Loot:Log attempt source=%s raidId=%s lootNid=%s "
    .. "looter=%s type=%s roll=%s lastBoss=%s"
E.LogLoggerNoRaidSession          = "[Logger] Loot:Log FAILED no raid session raidId=%s lootNid=%s"
E.LogLoggerItemNotFound           = "[Logger] Loot:Log FAILED item not found raidId=%d lootNid=%s lootCount=%d"
E.LogLoggerLooterEmpty            = "[Logger] Loot:Log looter empty raidId=%d lootNid=%s link=%s"
E.LogLoggerRollTypeNil            = "[Logger] Loot:Log rollType nil raidId=%d lootNid=%s looter=%s"
E.LogLoggerLootBefore             = "[Logger] Loot:Log BEFORE raidId=%d lootNid=%s link=%s "
    .. "prevLooter=%s prevType=%s prevRoll=%s"
E.LogLoggerLootOverwrite          = "[Logger] Loot overwrite raidId=%d lootNid=%s link=%s from=%s to=%s"
E.LogLoggerLootRecorded           = "[Logger] Loot recorded source=%s raidId=%d lootNid=%s link=%s -> "
    .. "looter=%s type=%s roll=%s"
E.LogLoggerVerifyFailed           = "[Logger] Loot:Log VERIFY FAILED raidId=%d lootNid=%s "
    .. "got(looter=%s type=%s roll=%s)"
E.LogLoggerVerified               = "[Logger] Loot:Log verified raidId=%d lootNid=%s"
E.LogLoggerRecordedNoBossContext  = "[Logger] Loot recorded without boss context raidId=%d lootNid=%s link=%s"
E.LogLoggerBossLootRemoved        = "[Logger] Boss delete removed loot raidId=%d bossId=%d removed=%d"
