local _, addon = ...

addon.E = addon.E or {}
local E = addon.E

-- ==================== Log Messages ==================== --
E.LogCoreCallbackHandlerMissing   = "[Core] CallbackHandler missing: using fallback event wiring"
E.LogCoreLoaded                   = "[Core] Loaded version=%s logLevel=%s perfMode=%s"
E.LogCoreEventsRegistered         = "[Core] Events registered=%d"
E.LogCorePlayerEnteringWorld      = "[Core] PLAYER_ENTERING_WORLD -> scheduling FirstCheck"
E.LogRaidLeftGroupEndSession      = "[Raid] Left group -> ending current raid session"
E.LogRaidRosterUpdate             = "[Raid] RosterUpdate v=%d num=%d"
E.LogRaidCreated                  = "[Raid] Created id=%d zone=%s size=%d players=%d"
E.LogRaidEnded                    = "[Raid] Ended id=%d zone=%s size=%d bosses=%d loot=%d duration=%d"
E.LogRaidCheck                    = "[Raid] Check zone=%s diff=%s current=%s"
E.LogRaidSessionChange            = "[Raid] Session change zone=%s size=%d diff=%d"
E.LogRaidSessionCreate            = "[Raid] Session create zone=%s size=%d diff=%d"
E.LogRaidFirstCheck               = "[Raid] FirstCheck inGroup=%s currentRaid=%s instance=%s type=%s diff=%s"
E.LogRaidPlayerJoin               = "[Raid] Player join name=%s raidId=%d"
E.LogRaidPlayerRefresh            = "[Raid] Player refresh name=%s raidId=%d"
E.LogRaidInstanceWelcome          = "[Raid] RAID_INSTANCE_WELCOME name=%s type=%s diff=%s nextReset=%s"
E.LogRaidUnmappedZone             = "[Raid] Unmapped raid zone: %s (diff=%s) -> no session check"
E.LogRaidInstanceRecognized       = "[Raid] Instance recognized: %s diff=%s -> check"
E.LogBossAddSkipped               = "[Boss] AddBoss skipped raidId=%s boss=%s"
E.LogBossLogged                   = "[Boss] Logged boss=%s diff=%d raid=%d players=%d"
E.LogBossLastBossHash             = "[Boss] lastBoss=%d hash=%s"
E.LogBossNoContextTrash           = "[Boss] No boss context -> creating _TrashMob_ bucket"
E.LogBossYellMatched              = "[Boss] Yell matched text=%s boss=%s"
E.LogBossUnitDiedMatched          = "[Boss] UNIT_DIED matched npcId=%d boss=%s"
E.LogLootParseFailed              = "[Loot] Parse failed msg=%s"
E.LogLootParsed                   = "[Loot] Parsed looter=%s link=%s count=%d"
E.LogLootIgnoredBelowThreshold    = "[Loot] Ignored below threshold rarity=%s thr=%d link=%s"
E.LogLootIgnoredItemId            = "[Loot] Ignored itemId=%s link=%s (ignoredItems)"
E.LogLootLogged                   = "[Loot] Logged raidId=%d itemId=%s bossNum=%s looter=%s"
E.LogLootFetchStart               = "[Loot] FetchLoot numLootItems=%d oldIndex=%d"
E.LogLootFetchDone                = "[Loot] FetchLoot done lootCount=%d currentIndex=%d"
E.LogLootItemInfoMissing          = "[Loot] ItemInfo missing -> deferred link=%s"
E.LogLootChatMsgLootRaw           = "[Loot] CHAT_MSG_LOOT raw=%s"
E.LogMLCandidateCacheBuilt        = "[ML] Candidate cache built item=%s candidates=%d"
E.LogMLAwardRequested             = "[ML] Award requested winner=%s type=%d roll=%d item=%s"
E.LogMLItemLocked                 = "[ML] ITEM_LOCKED bag=%s slot=%s link=%s count=%s soulbound=%s"
E.LogMLInventorySoulbound         = "[ML] Inventory item is soulbound -> cannot trade link=%s"
E.LogMLLootOpenedTrace            = "[ML] LOOT_OPENED items=%d fromInv=%s"
E.LogMLLootOpenedInfo             = "[ML] Loot opened items=%d fromInv=%s target=%s"
E.LogMLLootClosed                 = "[ML] LOOT_CLOSED opened=%s items=%d"
E.LogMLLootClosedCleanup          = "[ML] LOOT_CLOSED -> scheduling cleanup"
E.LogMLLootSlotCleared            = "[ML] LOOT_SLOT_CLEARED items=%d"
E.LogMLLootWindowEmptied          = "[ML] Loot window emptied"
E.LogMLCandidateCacheMiss         = "[ML] Candidate cache miss item=%s player=%s -> rebuild"
E.LogMLAwarded                    = "[ML] Awarded item=%s -> %s type=%d roll=%d slot=%d cand=%d"
E.LogMLAwardLoggerFailed          = "[ML] Awarded but Logger failed raidId=%s itemIndex=%s link=%s"
E.ErrMLMultiAwardInProgress       = "[ML] Multi-award in progress: wait until it finishes before awarding again."
E.LogTradeAcceptUpdate            = "[Trade] ACCEPT_UPDATE trader=%s winner=%s t=%s p=%s"
E.LogTradeCompleted               = "[Trade] Completed item=%s winner=%s type=%d roll=%d"
E.LogTradeLoggerLogFailed         = "[Trade] Logger log failed raidId=%s itemIndex=%s link=%s"
E.LogTradeKeepLoggerFailed        = "[Trade] Keep logged but Logger failed raidId=%s itemIndex=%s link=%s"
E.LogTradeStart                   = "[Trade] TradeItem start item=%s trader=%s target=%s type=%d roll=%d count=%d"
E.LogTradeTraderKeeps             = "[Trade] Trader keeps item=%s winner=%s"
E.LogTradeStackBlocked            = "[Trade] Stack trade blocked ignoreStacks=%s link=%s"
E.LogTradeInitiated               = "[Trade] Initiated item=%s -> %s"
E.LogTradeDelayedOutOfRange       = "[Trade] Delayed: %s out of range item=%s"
E.LogSRImportRequested            = "[SR] Import requested chars=%d"
E.LogSRItemInfoResolved           = "[SR] Item info resolved itemId=%d link=%s"
E.LogSRParseSkippedLine           = "[SR] ParseCSV skipped line=%s"
E.LogSRImportComplete             = "[SR] Import complete players=%d"
E.LogSRQueryMissingItems          = "[SR] QueryMissingItems updated=%s pending=%d"
E.LogLoggerLootLogAttempt         = "[Logger] Loot:Log attempt source=%s raidId=%s itemIndex=%s "
    .. "looter=%s type=%s roll=%s lastBoss=%s"
E.LogLoggerNoRaidSession          = "[Logger] Loot:Log FAILED no raid session raidId=%s itemIndex=%s"
E.LogLoggerItemNotFound           = "[Logger] Loot:Log FAILED item not found raidId=%d itemIndex=%s lootCount=%d"
E.LogLoggerLooterEmpty            = "[Logger] Loot:Log looter empty raidId=%d itemIndex=%s link=%s"
E.LogLoggerRollTypeNil            = "[Logger] Loot:Log rollType nil raidId=%d itemIndex=%s looter=%s"
E.LogLoggerLootBefore             = "[Logger] Loot:Log BEFORE raidId=%d itemIndex=%s link=%s "
    .. "prevLooter=%s prevType=%s prevRoll=%s"
E.LogLoggerLootOverwrite          = "[Logger] Loot overwrite raidId=%d itemIndex=%s link=%s from=%s to=%s"
E.LogLoggerLootRecorded           = "[Logger] Loot recorded source=%s raidId=%d itemIndex=%s link=%s -> "
    .. "looter=%s type=%s roll=%s"
E.LogLoggerVerifyFailed           = "[Logger] Loot:Log VERIFY FAILED raidId=%d itemIndex=%s "
    .. "got(looter=%s type=%s roll=%s)"
E.LogLoggerVerified               = "[Logger] Loot:Log verified raidId=%d itemIndex=%s"
E.LogLoggerRecordedNoBossContext  = "[Logger] Loot recorded without boss context raidId=%d itemIndex=%s link=%s"
E.LogLoggerBossLootRemoved        = "[Logger] Boss delete removed loot raidId=%d bossId=%d removed=%d"
