name: Luacheck Linter

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Lua and Luarocks
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.1 luarocks

    - name: Install Luacheck (local)
      run: luarocks install --local luacheck

    - name: Add luarocks bin to PATH
      run: echo "$HOME/.luarocks/bin" >> $GITHUB_PATH

    - name: Run Luacheck
      run: luacheck !KRT/
