name: Luacheck

on:
  push:
  pull_request:

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
        with:
          lua-version: "5.1"
      - uses: leafo/gh-actions-luarocks@v4
      - run: luarocks install luacheck
      - run: luacheck .
