name: Luacheck

on:
  push:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - '.github/workflows/luacheck.yml'
  pull_request:
    paths:
      - '**/*.lua'
      - '.luacheckrc'
      - '.github/workflows/luacheck.yml'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Run luacheck
        run: |
          luacheck '!KRT' --exclude-files '!KRT/Libs/**' --config .luacheckrc
