name: Luacheck Linter

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  luacheck:
    name: Run Luacheck on WoW addon
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Lua 5.1 and Luarocks
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.1 luarocks
        luarocks install luacheck

    - name: Add luarocks bin to PATH
      run: echo "$HOME/.luarocks/bin" >> $GITHUB_PATH

    - name: Run luacheck on !KRT/
      run: luacheck !KRT/
